sudo: required
dist: trusty

addons:
  chrome: stable

language: node_js

node_js:
  - "6"

# before_install:
#   - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

before_script:
  - sudo chown root /opt/google/chrome/chrome-sandbox
  - sudo chmod 4755 /opt/google/chrome/chrome-sandbox
  - ng server &

install:
  - yarn install --dev

script:
  - ng test --watch=false --code-coverage
  - yarn e2e
