dist: trusty

addons:
  chrome: stable

language: node_js

node_js:
  - "6"

before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

install:
  - yarn install --dev

script:
  - ng test --watch=false --code-coverage
  - yarn e2e
